[phases.setup]
nixPkgs = ['nodejs', 'python312', 'python312Packages.pip']

[phases.install]
cmds = [
    'cd frontend && npm install && npm run build && cd ..',
    'python3.12 -m pip install -r requirements.txt'
]

[start]
cmd = 'uvicorn backend.app:app --host 0.0.0.0 --port $PORT'
