version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_BASE_URL=${OPENROUTER_BASE_URL:-https://openrouter.ai/api/v1}
      - TEXT_MODEL=${TEXT_MODEL:-openai/gpt-3.5-turbo}
      - IMAGE_MODEL=${IMAGE_MODEL:-openai/dall-e-3}
      - TIMEOUT_SECS=${TIMEOUT_SECS:-60}
    ports:
      - "8000:8000"
    restart: unless-stopped
